<a href="https://colab.research.google.com/github/CharlesRajaR/ml_notebooks/blob/main/pytorch_deep_learning_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Author Details

* **Name:** Charles Raja R
* **Affiliation:** AI/ML/DL Researcher
* **Date:** 06-07-2026

In [ ]:
import torch

In [ ]:
torch.__version__

'2.11.0+cpu'

In [ ]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

6

In [ ]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
vector1 = torch.tensor([[1, 2], [2, 3]])
vector1.shape


torch.Size([2, 2])

In [ ]:
vector1.ndim

2

In [ ]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.9969, 0.5158, 0.6625, 0.2974],
        [0.4749, 0.7988, 0.4637, 0.7530],
        [0.5937, 0.9778, 0.4889, 0.5249]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
image_tensor = torch.rand(size=(224, 224, 3))

image_tensor

tensor([[[0.7040, 0.4867, 0.3745],
         [0.5747, 0.3371, 0.4619],
         [0.1912, 0.5158, 0.0017],
         ...,
         [0.8199, 0.0945, 0.3612],
         [0.8652, 0.7093, 0.4089],
         [0.9071, 0.3428, 0.1119]],

        [[0.5422, 0.5106, 0.4768],
         [0.2839, 0.8722, 0.1931],
         [0.2365, 0.3029, 0.7012],
         ...,
         [0.7786, 0.5927, 0.3289],
         [0.4592, 0.3358, 0.7314],
         [0.8931, 0.3524, 0.3694]],

        [[0.8187, 0.6347, 0.4969],
         [0.1939, 0.2591, 0.3649],
         [0.7012, 0.2253, 0.2953],
         ...,
         [0.3671, 0.2966, 0.2306],
         [0.7474, 0.7852, 0.9997],
         [0.4240, 0.6444, 0.6445]],

        ...,

        [[0.7506, 0.0677, 0.1754],
         [0.0804, 0.7022, 0.9585],
         [0.4130, 0.7817, 0.2283],
         ...,
         [0.4982, 0.4958, 0.7188],
         [0.9093, 0.4658, 0.2954],
         [0.3970, 0.7627, 0.7280]],

        [[0.5861, 0.1634, 0.9001],
         [0.8860, 0.5308, 0.7402],
         [0.

In [ ]:
image_tensor.ndim

3

In [ ]:
image_tensor.shape

torch.Size([224, 224, 3])

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.cuda

<module 'torch.cuda' from '/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py'>

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
a = torch.tensor([1,2,3])
a + 10

tensor([11, 12, 13])

In [ ]:
torch.multiply(a, a)

tensor([1, 4, 9])

In [ ]:
a @ a

tensor(14)

In [ ]:
torch.matmul(a, a)

tensor(14)

In [ ]:
a * 2

tensor([2, 4, 6])

In [ ]:
a / 2

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
torch.divide(a, 1)

tensor([1., 2., 3.])

In [ ]:
torch.subtract(a, 1)

tensor([0, 1, 2])

In [ ]:
a

tensor([1, 2, 3])

In [ ]:
a.T

/tmp/ipykernel_3169/2533872927.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  a.T


tensor([1, 2, 3])

In [ ]:
b = torch.rand(size=(2, 3))
b.T

tensor([[0.2689, 0.3566],
        [0.7338, 0.7392],
        [0.7798, 0.6623]])

In [ ]:
b

tensor([[0.2689, 0.7338, 0.7798],
        [0.3566, 0.7392, 0.6623]])

In [ ]:
torch.matmul(b, b.T)

tensor([[1.2189, 1.1548],
        [1.1548, 1.1122]])

In [ ]:
torch.mm(b, b.T)

tensor([[1.2189, 1.1548],
        [1.1548, 1.1122]])

Aggregation with Tensors

In [ ]:
x = torch.arange(0, 100, 11)
x

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [ ]:
x.min()

tensor(0)

In [ ]:
x.max()

tensor(99)

In [ ]:
x.dtype

torch.int64

In [ ]:
x.type(torch.float32).mean()

tensor(49.5000)

In [ ]:
x.sum()

tensor(495)

In [ ]:
arr = torch.arange(7, 77)
arr

tensor([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
        25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
        43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
        61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76])

In [ ]:
arr.argmin()

tensor(0)

In [ ]:
arr.argmax()

tensor(69)