<a href="https://colab.research.google.com/github/CharlesRajaR/ml_notebooks/blob/main/pytorch_deep_learning_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Author Details

* **Name:** Charles Raja R
* **Affiliation:** AI/ML/DL Researcher
* **Date:** 06-07-2026

In [1]:
import torch

In [2]:
torch.__version__

'2.11.0+cpu'

In [3]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

6

In [6]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
vector1 = torch.tensor([[1, 2], [2, 3]])
vector1.shape


torch.Size([2, 2])

In [10]:
vector1.ndim

2

In [11]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.0423, 0.2571, 0.1793, 0.6807],
        [0.2324, 0.5206, 0.7980, 0.0085],
        [0.9376, 0.3937, 0.6393, 0.3138]])

In [12]:
random_tensor.dtype

torch.float32

In [13]:
image_tensor = torch.rand(size=(224, 224, 3))

image_tensor

tensor([[[0.9242, 0.2094, 0.9362],
         [0.4618, 0.5449, 0.6590],
         [0.5376, 0.0631, 0.9382],
         ...,
         [0.5230, 0.1537, 0.0745],
         [0.4380, 0.2615, 0.9405],
         [0.7378, 0.1823, 0.7567]],

        [[0.5289, 0.5417, 0.7119],
         [0.1707, 0.6236, 0.7703],
         [0.5398, 0.8509, 0.5106],
         ...,
         [0.6958, 0.2304, 0.7105],
         [0.9145, 0.5456, 0.2170],
         [0.8476, 0.1604, 0.6843]],

        [[0.0664, 0.4266, 0.3073],
         [0.8460, 0.4061, 0.0568],
         [0.6932, 0.7573, 0.6895],
         ...,
         [0.5957, 0.4961, 0.2176],
         [0.2133, 0.9776, 0.1538],
         [0.1227, 0.2343, 0.5571]],

        ...,

        [[0.1814, 0.2582, 0.6084],
         [0.8381, 0.7663, 0.6374],
         [0.0829, 0.5189, 0.0045],
         ...,
         [0.2037, 0.3148, 0.1079],
         [0.9641, 0.4540, 0.2741],
         [0.3015, 0.6646, 0.8923]],

        [[0.7399, 0.9234, 0.9285],
         [0.6817, 0.9770, 0.2988],
         [0.

In [14]:
image_tensor.ndim

3

In [15]:
image_tensor.shape

torch.Size([224, 224, 3])

In [16]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
torch.cuda

<module 'torch.cuda' from '/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py'>

In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
a = torch.tensor([1,2,3])
a + 10

tensor([11, 12, 13])

In [22]:
torch.multiply(a, a)

tensor([1, 4, 9])

In [23]:
a @ a

tensor(14)

In [24]:
torch.matmul(a, a)

tensor(14)

In [25]:
a * 2

tensor([2, 4, 6])

In [26]:
a / 2

tensor([0.5000, 1.0000, 1.5000])

In [27]:
torch.divide(a, 1)

tensor([1., 2., 3.])

In [28]:
torch.subtract(a, 1)

tensor([0, 1, 2])

In [29]:
a

tensor([1, 2, 3])

In [30]:
a.T

/tmp/ipykernel_3136/2533872927.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  a.T


tensor([1, 2, 3])

In [31]:
b = torch.rand(size=(2, 3))
b.T

tensor([[0.3404, 0.6569],
        [0.6498, 0.0205],
        [0.1848, 0.7155]])

In [32]:
b

tensor([[0.3404, 0.6498, 0.1848],
        [0.6569, 0.0205, 0.7155]])

In [33]:
torch.matmul(b, b.T)

tensor([[0.5722, 0.3692],
        [0.3692, 0.9439]])

In [34]:
torch.mm(b, b.T)

tensor([[0.5722, 0.3692],
        [0.3692, 0.9439]])

Aggregation with Tensors

In [35]:
x = torch.arange(0, 100, 11)
x

tensor([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [36]:
x.min()

tensor(0)

In [37]:
x.max()

tensor(99)

In [38]:
x.dtype

torch.int64

In [39]:
x.type(torch.float32).mean()

tensor(49.5000)

In [40]:
x.sum()

tensor(495)

In [41]:
arr = torch.arange(7, 77)
arr

tensor([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
        25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
        43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
        61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76])

In [42]:
arr.argmin()

tensor(0)

In [43]:
arr.argmax()

tensor(69)

In [47]:
x = torch.arange(1, 9)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8]), torch.Size([8]))

In [49]:
x_reshaped = x.reshape(2, 4)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]),
 torch.Size([2, 4]))

In [53]:
z = x.view(2, 4)
z.shape, z

(torch.Size([2, 4]),
 tensor([[1, 2, 3, 4],
         [5, 6, 7, 8]]))

In [54]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
z[0][1] = 3
z[0][1]

tensor(3)

In [58]:
z

tensor([[1, 3, 3, 4],
        [5, 6, 7, 8]])

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [59]:
x

tensor([1, 3, 3, 4, 5, 6, 7, 8])

Stacking

In [62]:
x_stack = torch.stack([x,x,x], dim=1)
x_stack

tensor([[1, 1, 1],
        [3, 3, 3],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8]])

In [64]:
x_stack_parallel = torch.stack([x, x, x], dim = 0)
x_stack_parallel

tensor([[1, 3, 3, 4, 5, 6, 7, 8],
        [1, 3, 3, 4, 5, 6, 7, 8],
        [1, 3, 3, 4, 5, 6, 7, 8]])

In [70]:
x

tensor([1, 3, 3, 4, 5, 6, 7, 8])

In [68]:
torch.squeeze(x)

tensor([1, 3, 3, 4, 5, 6, 7, 8])

In [84]:
x.unsqueeze(dim=0).unsqueeze(dim=0).unsqueeze(dim=0).unsqueeze(dim=0)

tensor([[[[[1, 3, 3, 4, 5, 6, 7, 8]]]]])

In [90]:
x.unsqueeze(dim=1).unsqueeze(dim=1).unsqueeze(dim=1)

tensor([[[[1]]],


        [[[3]]],


        [[[3]]],


        [[[4]]],


        [[[5]]],


        [[[6]]],


        [[[7]]],


        [[[8]]]])

Permute

In [94]:
per = torch.rand(size=(3, 2, 1))

tensor([[[0.1128],
         [0.1443]],

        [[0.4783],
         [0.6357]],

        [[0.5249],
         [0.4644]]])

In [96]:
per.permute(2, 1, 0)

tensor([[[0.1128, 0.4783, 0.5249],
         [0.1443, 0.6357, 0.4644]]])

In [ ]:
per.permute()

Note: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

Indexing

In [98]:
a = torch.rand(3, 3, 4)
a

tensor([[[0.6339, 0.9996, 0.4560, 0.9088],
         [0.1007, 0.3153, 0.0225, 0.0259],
         [0.5749, 0.0670, 0.3320, 0.0266]],

        [[0.7326, 0.5934, 0.8906, 0.5036],
         [0.3144, 0.3485, 0.6057, 0.1391],
         [0.3830, 0.3391, 0.1037, 0.2870]],

        [[0.3773, 0.1868, 0.2815, 0.9420],
         [0.3946, 0.0847, 0.4994, 0.7368],
         [0.5852, 0.4810, 0.1268, 0.5734]]])

In [104]:
a[0, :, :]

tensor([[0.6339, 0.9996, 0.4560, 0.9088],
        [0.1007, 0.3153, 0.0225, 0.0259],
        [0.5749, 0.0670, 0.3320, 0.0266]])

In [107]:
a[0, :, 0]

tensor([0.6339, 0.1007, 0.5749])

In [106]:
a[0,0,:]

tensor([0.6339, 0.9996, 0.4560, 0.9088])

In [108]:
a[0, 0, 0] == a[0][0][0]

tensor(True)