<a href="https://colab.research.google.com/github/CharlesRajaR/ml_notebooks/blob/main/pytorch_deep_learning_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.__version__

'2.11.0+cpu'

In [3]:
scalar = torch.tensor(6)
scalar

tensor(6)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

6

In [6]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
vector1 = torch.tensor([[1, 2], [2, 3]])
vector1.shape


torch.Size([2, 2])

In [10]:
vector1.ndim

2

In [12]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.5367, 0.3502, 0.9293, 0.0125],
        [0.2397, 0.4591, 0.2169, 0.8161],
        [0.0732, 0.2643, 0.3857, 0.4586]])

In [13]:
random_tensor.dtype

torch.float32

In [14]:
image_tensor = torch.rand(size=(224, 224, 3))

image_tensor

tensor([[[0.3225, 0.3559, 0.0549],
         [0.9645, 0.4987, 0.7997],
         [0.6647, 0.9538, 0.9447],
         ...,
         [0.9865, 0.0782, 0.2369],
         [0.1882, 0.1804, 0.6242],
         [0.3613, 0.4217, 0.8514]],

        [[0.3124, 0.0259, 0.8423],
         [0.5993, 0.2599, 0.2310],
         [0.5230, 0.1446, 0.7686],
         ...,
         [0.0552, 0.0673, 0.6313],
         [0.3673, 0.7644, 0.9825],
         [0.6705, 0.3557, 0.5402]],

        [[0.3968, 0.2514, 0.9400],
         [0.6880, 0.0095, 0.8550],
         [0.4954, 0.2340, 0.2903],
         ...,
         [0.6393, 0.6207, 0.2024],
         [0.7517, 0.7632, 0.4304],
         [0.5734, 0.1165, 0.1983]],

        ...,

        [[0.7108, 0.5873, 0.8540],
         [0.1690, 0.1453, 0.7627],
         [0.4465, 0.1860, 0.4690],
         ...,
         [0.0431, 0.3703, 0.4610],
         [0.6177, 0.2448, 0.6822],
         [0.5771, 0.1103, 0.4792]],

        [[0.5947, 0.5396, 0.1149],
         [0.1726, 0.3321, 0.7755],
         [0.

In [15]:
image_tensor.ndim

3

In [16]:
image_tensor.shape

torch.Size([224, 224, 3])

In [17]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
torch.cuda

<module 'torch.cuda' from '/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py'>

In [21]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
a = torch.tensor([1,2,3])
a + 10

tensor([11, 12, 13])

In [23]:
torch.multiply(a, a)

tensor([1, 4, 9])

In [24]:
a @ a

tensor(14)

In [27]:
torch.matmul(a, a)

tensor(14)

In [25]:
a * 2

tensor([2, 4, 6])

In [26]:
a / 2

tensor([0.5000, 1.0000, 1.5000])

In [28]:
torch.divide(a, 1)

tensor([1., 2., 3.])

In [30]:
torch.subtract(a, 1)

tensor([0, 1, 2])

In [31]:
a

tensor([1, 2, 3])

In [32]:
a.T

/tmp/ipykernel_1479/2533872927.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  a.T


tensor([1, 2, 3])

In [33]:
b = torch.rand(size=(2, 3))
b.T

tensor([[0.0774, 0.1113],
        [0.1697, 0.7878],
        [0.0363, 0.6415]])

In [34]:
b

tensor([[0.0774, 0.1697, 0.0363],
        [0.1113, 0.7878, 0.6415]])

In [36]:
torch.matmul(b, b.T)

tensor([[0.0361, 0.1655],
        [0.1655, 1.0445]])

In [37]:
torch.mm(b, b.T)

tensor([[0.0361, 0.1655],
        [0.1655, 1.0445]])